INVENTORY_CAP = 10
WOOD = 'wood'
IRON = 'iron'
GOLD = 'gold'
LUMBER = 'lumber'
MITHRIL = 'mithril'
TREASURE = 'treasure'
WOODMILL = 'woodmill'
IRON_FORGE = 'ironForge'
GOLD_MINE = 'goldMine'
LUMBER_MILL = 'lumberMill'
MITHRIL_FORGE = 'mithrilForge'
TREASURE_MINE = 'treasureMine'
GRAND_SANCTUARY = 'grandSanctuary'
PHOENIX_FORGE = 'phoenixForge'
BANK_SMAUG = 'bankSmaug'
PEGASUS_CRUISER = 'pegasusCruiser'
FIRST_TIER_RESOURCE = [WOOD, IRON, GOLD]
SECOND_TIER_RESOURCE = [LUMBER, MITHRIL, TREASURE]
OBJECTIVES = [GRAND_SANCTUARY, PHOENIX_FORGE, BANK_SMAUG, PEGASUS_CRUISER]
FIRST_TIER_GENERATOR = { WOODMILL: 1, IRON_FORGE: 1, GOLD_MINE: 1 }
SECOND_TIER_GENERATOR = { LUMBER_MILL: 3, MITHRIL_FORGE: 3, TREASURE_MINE: 3}
COST = {
	LUMBER: { WOOD: 2 },
	MITHRIL: { IRON: 2 },
	TREASURE: {	GOLD: 2 },
	WOODMILL: { WOOD: 3, IRON: 1, GOLD: 1 },
	IRON_FORGE: { WOOD: 1, IRON: 3, GOLD: 1 },
	GOLD_MINE: { WOOD: 1, IRON: 1, GOLD: 3 },
	LUMBER_MILL: { WOODMILL: 1, LUMBER: 1, IRON: 1, GOLD: 1},
	MITHRIL_FORGE: { IRON_FORGE: 1, MITHRIL: 1, WOOD: 1, GOLD: 1},
	TREASURE_MINE: { GOLD_MINE: 1, TREASURE: 1, WOOD: 1, IRON: 1},
	GRAND_SANCTUARY: { LUMBER: 5, TREASURE: 2, MITHRIL: 2},
	PHOENIX_FORGE: { LUMBER: 2, TREASURE: 2, MITHRIL: 5},
	BANK_SMAUG: { LUMBER: 2, TREASURE: 5, MITHRIL: 2},
	PEGASUS_CRUISER: { LUMBER: 3, TREASURE: 3, MITHRIL: 3}
}

class LogicHandler(object):

	def __init__(self):
		